name: GLTScene
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython=0.29.21
  - numpy=1.19.1
  - networkx=2.5.1
  - pyrr=0.10.3
  - pyyaml=5.3.1
  - python=3.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pillow=7.2.0
  - scipy=1.5.2
  - tqdm=4.50.2
  - matplotlib=3.3.1
  - pip=24.3.1
  - pip:
    - wxpython==4.2.1
    - rtree==1.0.1
    - shapely==2.0.1
    - trimesh==3.23.3
    - simple_3dviz==0.7.0
    - pytorch-fast-transformers==0.4.0
    - scikit-learn==1.3.0