data:
    dataset_type: "cached_threedfront"
    encoding_type: "cached_autoregressive_wocm"
    dataset_directory: "../data/library/3D-FRONT"
    annotation_file: "../config/library_threed_front_splits.csv"
    path_to_invalid_scene_ids: "../config/invalid_threed_front_rooms.txt"
    path_to_invalid_bbox_jids: "../config/black_list.txt"
    filter_fn: "threed_front_library"
    augmentations: ["rotations"]
    train_stats: "dataset_stats.txt"
    room_layout_size: "64,64"
    walls_max: "11"
    eps: "1"
    min_samples: "2"
    cluster: "((('desk', 1), ('lounge_chair', 1)), 23)\n
                ((('desk', 1), ('dining_chair', 1)), 16)"


network:
    type: "autoregressive_transformer"
    n_layers: 4
    n_heads: 8
    query_dimensions: 64
    value_dimensions: 64
    feed_forward_dimensions: 512
    hidden2output_layer: "autoregressive_mlc"
    hidden_dims: 512
    with_extra_fc: false
    bbox_output: "autoregressive_mlc"
    n_mixtures: 10
    use_room_mask_as_features: true

feature_extractor:
    name: "resnet18"
    feature_size: 64
    freeze_bn: true
    input_channels: 1

training:
    splits: ["train", "val"]
    epochs: 10000
    steps_per_epoch: 500
    batch_size: 128
    save_frequency: 1
    optimizer: Adam
    lr: 0.0001
    weight_decay: 0.0

validation:
    splits: ["test"]
    frequency: 5
    batch_size: 128

logger:
    type: "wandb"
    project: "autoregressive_transformer"

